### ISSUE TITLE
Possibility of displaying IOB instead of basal

### ISSUE THREAD

**Issue by pettermork** [tynbendad/Garmin-CIQ-projects#1]
Hello!
Thank you for making this excellent watchface. I got myself a Garmin watch for the sole purpose of being able to keep an eye on my BG levels and your watchface is definitely helping me to do that. I do have a query though.
Would it be possible have a setting to display IOB instead of basal as it does now. I don't have a pump but I have a Nightscout site set up and I log my insulin doses via Spike so being able to also see my IOB would be a nice feature.

**Comment by tynbendad** [comment]
Hi, my watchfaces take IOB from the loop, openaps, or the medtronic
uploader since those are the most accurate if you're using those (if you
are using those the careportal IOB is still there but wrong.)
You could take my source and build your own with a small change to display
the careportal (aka nightscout) one instead. Or, you might want to try my
app "CGM Loop" which I think will show the careportal IOB if its there...
Hope that helps. Regards,
j

**Comment by pettermork** [comment]
Thank you for you reply. I understand you can’t make a custom build for everyone of your users. I shall give it a try.

regards
